"""Put run reports side by side, so a claimed improvement has a source.

    py scripts/compare_runs.py run-report run-report-ourloop run-report-ourloop-400

Each argument names an `artifacts/<name>.json` written by `scripts/analyze_run.py`.
Writes `artifacts/comparison.json` and prints the table.

Why a script and not a hand-typed table in a note: every number in this project has to
trace to an artifact that can be regenerated (CLAUDE.md §3). A table typed by hand is a
number produced from memory, which is exactly the thing that goes stale and then gets
quoted in an interview.

It compares only what the analyser recomputes from the recordings themselves, so two runs
are always measured the same way. Rates are per-run, because the runs deliberately have
different budgets — comparing raw counts across an 80- and a 400-action run would be a
straightforward lie.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "artifacts"

ROWS = [
    ("agent", lambda r: r["agent"]),
    ("actions", lambda r: r["actions"]),
    ("final score", lambda r: r["final_score"]),
    ("final state", lambda r: r["final_state"]),
    ("actions not available", lambda r: r["actions_not_available"]),
    ("  as % of budget", lambda r: _pct(r["actions_not_available"], r["actions"])),
    ("actions that changed nothing", lambda r: r["transitions_no_change"]),
    ("  as % of budget", lambda r: _pct(r["transitions_no_change"], r["actions"])),
    ("GAME_OVER frames", lambda r: r.get("game_over_frames", "n/a")),
    ("RESETs sent", lambda r: r.get("resets_sent", "n/a")),
    ("distinct actions used", lambda r: len(r.get("actions_sent_histogram", {}))),
    ("most-repeated action", lambda r: _mode(r.get("actions_sent_histogram", {}))),
]


def _mode(hist: dict) -> str:
    """The action the agent leant on hardest — a cheap read on a stuck policy."""
    if not hist:
        return "n/a"
    key, n = max(hist.items(), key=lambda kv: kv[1])
    total = sum(hist.values())
    return f"id {key}: {n}/{total} ({100 * n / total:.0f}%)"


def _pct(n: int, total: int) -> str:
    return f"{100 * n / total:.1f}%" if total else "n/a"


def load(name: str) -> dict:
    path = ARTIFACTS / f"{name.removesuffix('.json')}.json"
    if not path.exists():
        raise SystemExit(f"no such report: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 1
    reports = [load(a) for a in argv]

    labels = [f"run {i + 1}" for i in range(len(reports))]
    width = max(len(label) for label, _ in ROWS)
    cols = max(28, max(len(str(r["agent"])) for r in reports) // len(reports) + 8)

    print(f"{'':{width}}  " + "  ".join(f"{lbl:>{cols}}" for lbl in labels))
    print("-" * (width + 2 + (cols + 2) * len(reports)))
    for label, get in ROWS:
        cells = []
        for r in reports:
            v = str(get(r))
            cells.append(f"{v[:cols]:>{cols}}" if len(v) > cols else f"{v:>{cols}}")
        print(f"{label:{width}}  " + "  ".join(cells))

    print()
    for i, r in enumerate(reports, 1):
        print(f"run {i}: {r['agent']}  [{r['recording']}]")

    out = ARTIFACTS / "comparison.json"
    out.write_text(
        json.dumps(
            {
                "note": (
                    "generated by scripts/compare_runs.py from the named run reports; "
                    "every field is recomputed from the committed recordings"
                ),
                "runs": [
                    {
                        "report": name,
                        "agent": r["agent"],
                        "recording": r["recording"],
                        "actions": r["actions"],
                        "final_score": r["final_score"],
                        "final_state": r["final_state"],
                        "actions_not_available": r["actions_not_available"],
                        "actions_not_available_pct": _pct(
                            r["actions_not_available"], r["actions"]
                        ),
                        "transitions_no_change": r["transitions_no_change"],
                        "transitions_no_change_pct": _pct(
                            r["transitions_no_change"], r["actions"]
                        ),
                        "game_over_frames": r.get("game_over_frames"),
                        "resets_sent": r.get("resets_sent"),
                    }
                    for name, r in zip(argv, reports)
                ],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
